export const roles =
    ATTR_TABLE = 'roles',
    ATTR_CHAR_DESCRIPTION = 'description',
    ATTR_CHAR_ID = 'id',
    ATTR_DATETIME_CREATED_AT = 'created_at',
    ATTR_DATETIME_DELETED_AT = 'deleted_at',
    ATTR_DATETIME_UPDATED_AT = 'updated_at',
    ATTR_INT_CREATED_BY = 'created_by_id',
    ATTR_INT_UPDATED_BY = 'updated_by_id',
    ATTR_RELATION_UPDATED_BY = 'updated_by',
    ATTR_RELATION_CREATED_BY = 'created_by',
    ATTR_RELATION_MODULES = 'modules',
    ATTR_RELATION_ORGANIZATION = 'organization'
