export const userRoles =
  ATTR_TABLE = 'user_roles',
  ATTR_CHAR_ID = 'id',
  ATTR_DATETIME_CREATED_AT = 'created_at',
  ATTR_DATETIME_DELETED_AT = 'deleted_at',
  ATTR_DATETIME_UPDATED_AT = 'updated_at',
  ATTR_INT_CREATED_BY = 'created_by_id',
  ATTR_INT_ROLE = 'role_id',
  ATTR_INT_UPDATED_BY = 'updated_by_id',
  ATTR_INT_USER = 'user_id',
  ATTR_RELATION_UPDATED_BY = 'updated_by',
  ATTR_RELATION_CREATED_BY = 'created_by',
  ATTR_RELATION_ROLE = 'role',
  ATTR_RELATION_USER = 'user'
